[mysqld]
server-id=2 #服务器唯一标识符，必须与主库和其他从库不同
relay-log=relay-bin #启用中继日志，并设置基础名称
read-only=1 #设置从库为只读模式（对普通用户）

#项目中只有一个mysql-slave.conf文件
#Docker容器化部署的配置机制
#每个MySQL从库容器都有自己独立的运行环境，包括：
#  - 独立的文件系统
#  - 独立的配置文件
#  - 独立的数据目录
#  所以项目中只使用一个mysql-slave.conf文件是合理的Docker化设计，通过容器化技术实现了配置的复用和环境的隔离。
#