# Sentinel 1 Configuration
port 26379
daemonize no
pidfile /var/run/redis-sentinel.pid
loglevel notice
logfile ""
dir /data

# Sentinel monitoring configuration
# sentinel monitor <master-name> <master-ip> <master-port> <quorum>
sentinel monitor mymaster redis-master 6379 2

# Failover timeout (ms)
sentinel failover-timeout mymaster 180000

# Parallel sync (how many slaves can sync at the same time)
sentinel parallel-syncs mymaster 1

# Down after milliseconds
sentinel down-after-milliseconds mymaster 5000

# Deny scripts reconfig
sentinel deny-scripts-reconfig yes
